
    
    create table acct_authority (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    ) ;

    create table acct_role (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    ) ;

    create table acct_role_authority (
        role_id bigint not null,
        authority_id bigint not null
    ) ;

    create table acct_user (
        id bigint generated by default as identity,
        email varchar(255),
        login_name varchar(255) not null unique,
        name varchar(255),
        password varchar(255),
        primary key (id)
    ) ;
    
    create table acct_user_role (
        user_id bigint not null,
        role_id bigint not null
    ) ;
    
    --mine table
    
    create table people (
    	id bigint generated by default as identity,
    	name varchar(255) not null,
    	sex varchar(255) not null
    ) ;
    
    create table marriage (
    	id bigint generated by default as identity,
    	husband_id bigint not null,
    	wife_id bigint not null
    );
    
    create table children (
    	id bigint generated by default as identity,
    	marriage_id bigint not null,
    	people_id bigint not null
    );
    
    